import { Customers } from './CustomerApi';

export const initialCustomers: Customers = [
  
  {
    name: 'Agnes Carney',
    isCool: true,
    age: 38,
    color: 'pink',
  },
  {
    name: 'Nichole Le',
    isCool: true,
    age: 24,
    color: 'rebeccapurple',
  },
  {
    name: 'Vilma Schroeder',
    isCool: true,
    age: 28,
    color: 'red',
  },
  {
    name: 'Eve Bruce',
    isCool: false,
    age: 35,
    color: 'red',
  },
  {
    name: 'Delgado Albert',
    isCool: true,
    age: 25,
    color: 'pink',
  },
  {
    name: 'Annette Simon',
    isCool: false,
    age: 30,
    color: 'red',
  },
  {
    name: 'Margo Pitts',
    isCool: true,
    age: 32,
    color: 'grey',
  },
  {
    name: 'Garrett Coffey',
    isCool: true,
    age: 20,
    color: 'rebeccapurple',
  },
  {
    name: 'Belinda Bullock',
    isCool: true,
    age: 26,
    color: 'grey',
  },
  {
    name: 'Alvarez Christian',
    isCool: true,
    age: 30,
    color: 'rebeccapurple',
  },
  {
    name: 'Castaneda Aguirre',
    isCool: false,
    age: 29,
    color: 'rebeccapurple',
  },
  {
    name: 'Shaffer Gibbs',
    isCool: true,
    age: 32,
    color: 'red',
  },
  {
    name: 'Castillo Hayden',
    isCool: true,
    age: 34,
    color: 'rebeccapurple',
  },
  {
    name: 'Hill James',
    isCool: true,
    age: 40,
    color: 'grey',
  },
  {
    name: 'Milagros Good',
    isCool: true,
    age: 23,
    color: 'rebeccapurple',
  },
  {
    name: 'Robles Maxwell',
    isCool: false,
    age: 22,
    color: 'rebeccapurple',
  },
  {
    name: 'Elvia Wilkinson',
    isCool: true,
    age: 40,
    color: 'pink',
  },
  {
    name: 'Guzman Velazquez',
    isCool: false,
    age: 28,
    color: 'grey',
  },
  {
    name: 'Ofelia Foreman',
    isCool: false,
    age: 24,
    color: 'grey',
  },
  {
    name: 'Rosella Duncan',
    isCool: true,
    age: 33,
    color: 'pink',
  },
  {
    name: 'William Keith',
    isCool: false,
    age: 35,
    color: 'rebeccapurple',
  },
  {
    name: 'Virgie Hartman',
    isCool: false,
    age: 37,
    color: 'red',
  },
  {
    name: 'Petty Gould',
    isCool: true,
    age: 20,
    color: 'rebeccapurple',
  },
  {
    name: 'Rojas Poole',
    isCool: true,
    age: 23,
    color: 'grey',
  },
  {
    name: 'Stanton Wilder',
    isCool: true,
    age: 22,
    color: 'pink',
  },
];
